### ISSUE TITLE
Add the cansim package for R-based API access to statistics from Statistics Canada

### ISSUE THREAD

**Issue by PhilSmith26** [SNStatComp/awesome-official-statistics-software#13]

**Comment by PhilSmith26** [comment]
I suggest you add the cansim package to the list. It is used in R to connect to the API that gives access to Statistics Canada tables.

**Comment by markvanderloo** [comment]
Hi Phil,

Is there a plan to publish this package on CRAN? We prefer CRAN releases since it implies a large number of technical checks.

**Comment by markvanderloo** [comment]
Thanks! I was searching for CANSIM and the [GH page](https://github.com/mountainMath/cansim) of that package still has an 'not published' badge.

It has now been added to the awesomelist. Please warn the authors that they can now wear the badge by adding 

```
[![Mentioned in Awesome Official Statistics ](https://awesome.re/mentioned-badge.svg)](http://www.awesomeofficialstatistics.org)
```

to their github `README.md`
