### ISSUE TITLE
 recommend packages easySdcTable and SmallCountRounding

### ISSUE THREAD

**Issue by olangsrud** [SNStatComp/awesome-official-statistics-software#14]
I recommend the two packages  easySdcTable and SmallCountRounding to be listed under Statistical disclosure control.

They may be described similarly to the description at the CRAN Task View for Official Statistics & Survey Methodology:

R package easySdcTable provide an interface to the package sdcTable.
R package SmallCountRounding can be used to protect frequency tables by rounding necessary inner cells so that cross-classifications to be published are safe.

These packages are implemented within a modernized IT system at Statistics Norway and they are used for production purposes.

**Comment by markvanderloo** [comment]
Thanks Øyvind! Packages are now added under 'SDC'.

**Comment by olangsrud** [comment]
Thanks Mark! But the links are not working. Correct links:

https://cran.r-project.org/package=easySdcTable
https://cran.r-project.org/package=SmallCountRounding

**Comment by markvanderloo** [comment]
Ah, I see. Thanks for the check. Also: don't forget to wear the badge by adding the following line to the github README.md (if there is any)

```
[![Mentioned in Awesome Official Statistics ](https://awesome.re/mentioned-badge.svg)](http://www.awesomeofficialstatistics.org)
```

**Comment by olangsrud** [comment]
Thank you! Now the badge is added to the README.md files. Nice :)
