### ISSUE TITLE
non-working URL in README

### ISSUE THREAD

**Issue by bernhard-da** [SNStatComp/awesome-official-statistics-software#17]
hi everybody.

in the README, it is described under *Wear the badge*, how to use the badge. However, the URL in the example [http://www.awesomeofficialstatistics.org](http://www.awesomeofficialstatistics.org) is not working right now. perhaps this should be changed to the URL of the github repo?

**Comment by markvanderloo** [comment]
Hi Bernhard,

I checked it against the awesome badge on this repo:
https://github.com/data-cleaning/validate and it works there. Could it be a
browser issue preventing redirects or something?

-Mark

**Comment by bernhard-da** [comment]
i only realized this because i got a note from win-builder that the url was unreachable and additionally i couldn't open it from my work pc too. perhaps it was just strange coincidence that the site was offline for a short time...
