### ISSUE TITLE
pxweb and PxWebApiData

### ISSUE THREAD

**Issue by olangsrud** [SNStatComp/awesome-official-statistics-software#18]
I suggest the CRAN-packages pxweb and PxWebApiData to be added under "Access to official statistics".

R package pxweb. Generic interface for the PX-Web/PC-Axis API used by many National Statistical Agencies.

R package PxWebApiData. Easy API access to e.g. Statistics Norway, Statistics Sweden and Statistics Finland.

**Comment by markvanderloo** [comment]
Thanks! added to the list.

**Comment by olangsrud** [comment]
Thanks! I will add the badge.
