### ISSUE TITLE
spiR

### ISSUE THREAD

**Issue by warint** [SNStatComp/awesome-official-statistics-software#28]
Dear Olav,
you might find my latest package interesting for the section about official statistics: https://CRAN.R-project.org/package=spiR
thanks a ton,
WR,
Thierry

**Comment by donthebike** [comment]
Dear Thierry,
Thanks for notifying, very interesting.
However the SPI is published by the Social Progress Imperative which is apparently a global non profit organisation asking for donations and this organisation is not a member of the official statistics community itself.
So, to keep the list focused on the core target of producting or accessing official statistics, we choose to leave it out.
Thanks anyway,
WR,
Olav

**Comment by warint** [comment]
Ok i understand, thanks,
Th

http://warin.nuance-r.com

________________________________
