### ISSUE TITLE
add asdfree.com / lodown package

### ISSUE THREAD

**Issue by hannesmuehleisen** [SNStatComp/awesome-official-statistics-software#3]
See https://github.com/ajdamico/lodown & http://www.asdfree.com/

**Comment by markvanderloo** [comment]
Hey Hannes, thanks for suggesting. We'll keep it in mind but we're not adding it just yet: the installation instructions are missing from the README and also there seems to be no stable release. For users that are not devs themselves this is a big hurdle.
