### ISSUE TITLE
Feature extension: last code change

### ISSUE THREAD

**Issue by olavtenbosch** [SNStatComp/awesome-official-statistics-software#36]
The idea was suggested to add to each item the last code change of the particular item, thus giving an indication of the maintenance activity of the package, derived from the source code control system it uses.

**Comment by djvanderlaan** [comment]
As a possible start: the following code gets the last updated dates for CRAN-packages. 

```
library(rvest)

dta <- read.csv("data/software.csv")


cran <- grep("^http[s]?://(CRAN|cran).*package=.*$", dta$link)

dates <- as.Date(rep(NA, length(cran)))
for (i in seq_along(cran)) {
  try({
    h <- read_html(dta$link[cran[i]])
    tab <- h %>% html_element("table") %>% html_table()
    published <- tab[[2]][grep("^Published:", tab[[1]])]
    dates[i] <- as.Date(published)
  })
}

dta$last_updated <- as.Date(NA)
dta$last_updated[cran] <- dates
```

**Comment by olavtenbosch** [comment]
Just implemented badges on the list.
What type of repo (Cran/GitHub/GitLab/NPM/Pypi), last release or change (if available) and license (if available).
Badges will be updated weekly.
