### ISSUE TITLE
Adding pysdmx to the software list

### ISSUE THREAD

**Issue by sosna** [SNStatComp/awesome-official-statistics-software#58]
Dear all,

We would like suggesting to add pysdmx to the list of software. 

As mentioned on the [project main page](https://github.com/bis-med-it/pysdmx), "pysdmx is a pragmatic and opinionated library written in Python. It focuses on simplicity, providing a subset of SDMX functionalities without requiring advanced knowledge of SDMX."

Do you think that would be possible?

Thank you in advance!

Xavier

**Comment by olavtenbosch** [comment]
Hi Xavier,
Thanks for mentioning and indeed it's a good idea to add.
I just added it under the "Process" GSBPM category.
Looking forward to the first non-rc 1.0.0 release .... so keep it going :-)
regards, Olav

**Comment by sosna** [comment]
Thanks a lot, Olav. It should be coming this month :)
