### ISSUE TITLE
Missing JSON-stat libraries

### ISSUE THREAD

**Issue by badosa** [SNStatComp/awesome-official-statistics-software#59]
The awesome-official-statistics-software list 3 JSON-stat libraries:

* R package [rjstat](https://cran.r-project.org/package=rjstat). Read and write data sets in the JSON-stat format.
* Python [pyjstat](https://pypi.org/project/pyjstat/). Read and write JSON-stat.
* Java application [json-stat.java](https://github.com/statisticsnorway/json-stat.java). Read and write JSON-stat. By Statistics Norway.

but there are more libraries for JSON-stat (see [JSON-stat Tools](https://json-stat.org/tools/)). Please include those too. For example:

**JSON-stat Toolkit (several solutions that also supports SDMX-JSON)**

It includes the [JSON-stat JavaScript Toolkit](https://www.npmjs.com/package/jsonstat-toolkit), the [JSON-stat Javascript Utilities Suite](https://www.npmjs.com/package/jsonstat-suite), the [JSON-stat Command Line Conversion Tools](https://www.npmjs.com/package/jsonstat-conv) and [JSON-stat for Eurostat](https://www.npmjs.com/package/jsonstat-euro).

**JSONStat.jl (JSON-stat library for the Julia language)**

https://github.com/klpn/JSONStat.jl

Besides these general tools, [JSON-stat Tools](https://json-stat.org/tools/) also lists more specific tools, for example to deal with Eurostat datasets (like [Eurostat R package](https://ropengov.github.io/eurostat/) or [Eurostat’s Swiss Army Knife](https://jsonstat.com/eurostat/)) or to batch-retrieve JSON-stat datasets in CSV form ([JSON-stat CSV Batch Exporter](https://json-stat.org/format/exporter/batch/)).

If you want I can create a pull request with these additions.

**Comment by olavtenbosch** [comment]
Dear Xavier,
Thanks for mentioning.
We just added a link to the JSON-stat tools page at the JSON-STAT entry in dissemination and an entry for the JSON-stat toolkit, with three links to some of the most important packages in there in the description text.
Kind regards,
Olav
